# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arsouze/Documents/Modeles/Codes/OpenAlea/plantscan3d/src/openalea/plantscan3d/segmenteditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gleditor = GLSegmentEditor(self.centralwidget)
        self.gleditor.setObjectName("gleditor")
        self.gridLayout.addWidget(self.gleditor, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 22))
        self.menubar.setObjectName("menubar")
        self.menuTrees = QtWidgets.QMenu(self.menubar)
        self.menuTrees.setObjectName("menuTrees")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_Points = QtWidgets.QAction(MainWindow)
        self.actionExport_Points.setObjectName("actionExport_Points")
        self.actionExport_To_Database = QtWidgets.QAction(MainWindow)
        self.actionExport_To_Database.setEnabled(False)
        self.actionExport_To_Database.setObjectName("actionExport_To_Database")
        self.menuFile.addAction(self.actionExport_Points)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_To_Database)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTrees.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Segmentation Editor"))
        self.menuTrees.setTitle(_translate("MainWindow", "Trees"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExport_Points.setText(_translate("MainWindow", "Export Points"))
        self.actionExport_To_Database.setText(_translate("MainWindow", "Export To Database"))
from .glsegmenteditor import GLSegmentEditor
