# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arsouze/Documents/Modeles/Codes/OpenAlea/plantscan3d/src/openalea/plantscan3d/database/connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(393, 148)
        Dialog.setMinimumSize(QtCore.QSize(393, 148))
        Dialog.setMaximumSize(QtCore.QSize(393, 148))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameHLayout = QtWidgets.QHBoxLayout()
        self.usernameHLayout.setObjectName("usernameHLayout")
        self.usernameLabel = QtWidgets.QLabel(Dialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameHLayout.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.usernameHLayout.addWidget(self.usernameLineEdit)
        self.verticalLayout.addLayout(self.usernameHLayout)
        self.passwordHLayout = QtWidgets.QHBoxLayout()
        self.passwordHLayout.setObjectName("passwordHLayout")
        self.passwordLabel = QtWidgets.QLabel(Dialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordHLayout.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(Dialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordHLayout.addWidget(self.passwordLineEdit)
        self.verticalLayout.addLayout(self.passwordHLayout)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Connection"))
        self.usernameLabel.setText(_translate("Dialog", "Username :"))
        self.passwordLabel.setText(_translate("Dialog", "Password :"))
        self.checkBox.setText(_translate("Dialog", "Remember"))
