# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arsouze/Documents/Modeles/Codes/OpenAlea/plantscan3d/src/openalea/plantscan3d/database/database_item.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(634, 380)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.thumbnailLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnailLabel.sizePolicy().hasHeightForWidth())
        self.thumbnailLabel.setSizePolicy(sizePolicy)
        self.thumbnailLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.thumbnailLabel.setScaledContents(False)
        self.thumbnailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnailLabel.setObjectName("thumbnailLabel")
        self.horizontalLayout.addWidget(self.thumbnailLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 334, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.propertiesVLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.propertiesVLayout.setObjectName("propertiesVLayout")
        self.nameHLayout = QtWidgets.QHBoxLayout()
        self.nameHLayout.setObjectName("nameHLayout")
        self.nameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLabel.setObjectName("nameLabel")
        self.nameHLayout.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameEdit.setObjectName("nameEdit")
        self.nameHLayout.addWidget(self.nameEdit)
        self.propertiesVLayout.addLayout(self.nameHLayout)
        self.storageHLayout = QtWidgets.QHBoxLayout()
        self.storageHLayout.setObjectName("storageHLayout")
        self.storageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.storageLabel.setObjectName("storageLabel")
        self.storageHLayout.addWidget(self.storageLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.storageComboBox = MyComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storageComboBox.sizePolicy().hasHeightForWidth())
        self.storageComboBox.setSizePolicy(sizePolicy)
        self.storageComboBox.setEditable(True)
        self.storageComboBox.setObjectName("storageComboBox")
        self.storageComboBox.addItem("")
        self.verticalLayout.addWidget(self.storageComboBox)
        self.protocolComboBox = MyComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protocolComboBox.sizePolicy().hasHeightForWidth())
        self.protocolComboBox.setSizePolicy(sizePolicy)
        self.protocolComboBox.setEditable(False)
        self.protocolComboBox.setObjectName("protocolComboBox")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.verticalLayout.addWidget(self.protocolComboBox)
        self.storageHLayout.addLayout(self.verticalLayout)
        self.propertiesVLayout.addLayout(self.storageHLayout)
        self.editTagsButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.editTagsButton.setObjectName("editTagsButton")
        self.propertiesVLayout.addWidget(self.editTagsButton)
        self.dateHLayout = QtWidgets.QHBoxLayout()
        self.dateHLayout.setObjectName("dateHLayout")
        self.dateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateLabel.setObjectName("dateLabel")
        self.dateHLayout.addWidget(self.dateLabel)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.scrollAreaWidgetContents)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateHLayout.addWidget(self.dateTimeEdit)
        self.propertiesVLayout.addLayout(self.dateHLayout)
        self.pointNbHLayout = QtWidgets.QHBoxLayout()
        self.pointNbHLayout.setObjectName("pointNbHLayout")
        self.pointNumberLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointNumberLabel.sizePolicy().hasHeightForWidth())
        self.pointNumberLabel.setSizePolicy(sizePolicy)
        self.pointNumberLabel.setObjectName("pointNumberLabel")
        self.pointNbHLayout.addWidget(self.pointNumberLabel)
        self.pointNumberSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointNumberSpinBox.sizePolicy().hasHeightForWidth())
        self.pointNumberSpinBox.setSizePolicy(sizePolicy)
        self.pointNumberSpinBox.setFrame(True)
        self.pointNumberSpinBox.setReadOnly(True)
        self.pointNumberSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pointNumberSpinBox.setMaximum(999999999)
        self.pointNumberSpinBox.setObjectName("pointNumberSpinBox")
        self.pointNbHLayout.addWidget(self.pointNumberSpinBox)
        self.propertiesVLayout.addLayout(self.pointNbHLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.addPropertiesButton = QtWidgets.QPushButton(Dialog)
        self.addPropertiesButton.setObjectName("addPropertiesButton")
        self.verticalLayout_3.addWidget(self.addPropertiesButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Browse Item"))
        self.thumbnailLabel.setText(_translate("Dialog", "Image"))
        self.nameLabel.setText(_translate("Dialog", "Name :"))
        self.storageLabel.setText(_translate("Dialog", "Storage server :"))
        self.storageComboBox.setItemText(0, _translate("Dialog", "194.199.236.63"))
        self.protocolComboBox.setItemText(0, _translate("Dialog", "ftp"))
        self.protocolComboBox.setItemText(1, _translate("Dialog", "http"))
        self.editTagsButton.setText(_translate("Dialog", "Edit tags"))
        self.dateLabel.setText(_translate("Dialog", "Last Modification Date :"))
        self.pointNumberLabel.setText(_translate("Dialog", "Point Number :"))
        self.addPropertiesButton.setText(_translate("Dialog", "Add Properties"))
from .mycombobox import MyComboBox
from . import database_rc
