# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/arsouze/Documents/Modeles/Codes/OpenAlea/plantscan3d/src/openalea/plantscan3d/database/db_connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(378, 193)
        Dialog.setMinimumSize(QtCore.QSize(378, 193))
        Dialog.setMaximumSize(QtCore.QSize(378, 193))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addressHLayout = QtWidgets.QHBoxLayout()
        self.addressHLayout.setObjectName("addressHLayout")
        self.addressLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressLabel.sizePolicy().hasHeightForWidth())
        self.addressLabel.setSizePolicy(sizePolicy)
        self.addressLabel.setObjectName("addressLabel")
        self.addressHLayout.addWidget(self.addressLabel)
        self.addressComboBox = QtWidgets.QComboBox(Dialog)
        self.addressComboBox.setEditable(True)
        self.addressComboBox.setObjectName("addressComboBox")
        self.addressComboBox.addItem("")
        self.addressHLayout.addWidget(self.addressComboBox)
        self.verticalLayout.addLayout(self.addressHLayout)
        self.IDGroupBox = QtWidgets.QGroupBox(Dialog)
        self.IDGroupBox.setMinimumSize(QtCore.QSize(354, 105))
        self.IDGroupBox.setMaximumSize(QtCore.QSize(354, 105))
        self.IDGroupBox.setFlat(True)
        self.IDGroupBox.setCheckable(True)
        self.IDGroupBox.setChecked(False)
        self.IDGroupBox.setObjectName("IDGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.IDGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usernameHLayout = QtWidgets.QHBoxLayout()
        self.usernameHLayout.setObjectName("usernameHLayout")
        self.usernameLabel = QtWidgets.QLabel(self.IDGroupBox)
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameHLayout.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.IDGroupBox)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.usernameHLayout.addWidget(self.usernameLineEdit)
        self.verticalLayout_2.addLayout(self.usernameHLayout)
        self.passwordHLayout = QtWidgets.QHBoxLayout()
        self.passwordHLayout.setObjectName("passwordHLayout")
        self.passwordLabel = QtWidgets.QLabel(self.IDGroupBox)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordHLayout.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.IDGroupBox)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordHLayout.addWidget(self.passwordLineEdit)
        self.verticalLayout_2.addLayout(self.passwordHLayout)
        self.verticalLayout.addWidget(self.IDGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Database Connection"))
        self.addressLabel.setText(_translate("Dialog", "Address :"))
        self.addressComboBox.setItemText(0, _translate("Dialog", "194.199.236.63:27017"))
        self.IDGroupBox.setTitle(_translate("Dialog", "Identification"))
        self.usernameLabel.setText(_translate("Dialog", "Username :"))
        self.passwordLabel.setText(_translate("Dialog", "Password :"))
